# Generated by Django 5.2.14 on 2026-05-05 17:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('meat_type', models.CharField(choices=[('BEEF', 'Beef'), ('MUTTON', 'Mutton'), ('CHICKEN', 'Chicken'), ('GOAT', 'Goat'), ('HORSE', 'Horse'), ('OTHER', 'Other')], db_index=True, max_length=10, verbose_name='meat type')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='quantity (kg)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per kg')),
                ('location', models.CharField(db_index=True, max_length=200, verbose_name='location')),
                ('available_from', models.DateField(verbose_name='available from')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD_OUT', 'Sold out'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10, verbose_name='status')),
                ('supplier', models.ForeignKey(limit_choices_to={'role': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'meat_type', 'location'], name='listings_li_status_c77037_idx')],
            },
        ),
    ]
