# Generated by Django 5.2.14 on 2026-05-10 22:30

import apps.listings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cold_chain',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('CHILLED', 'Chilled'), ('FROZEN', 'Frozen')], db_index=True, default='FRESH', max_length=10, verbose_name='cold chain'),
        ),
        migrations.AddField(
            model_name='listing',
            name='freshness_date',
            field=models.DateField(blank=True, null=True, verbose_name='freshness date (slaughter date)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='halal_certified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='halal certified'),
        ),
        migrations.AddField(
            model_name='listing',
            name='service_area_csv',
            field=models.CharField(blank=True, help_text='Comma-separated region names the supplier delivers to', max_length=500, verbose_name='service areas (comma-separated)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.listings.models._listing_photo_path, verbose_name='image')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first; 0 is the primary thumbnail', verbose_name='position')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'verbose_name': 'listing photo',
                'verbose_name_plural': 'listing photos',
                'ordering': ('position', 'id'),
            },
        ),
    ]
