# Generated by Django 5.2.14 on 2026-05-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_cold_chain_listing_freshness_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-safe key; auto-generated from Uzbek name if left blank', max_length=80, unique=True, verbose_name='slug')),
                ('name_uz', models.CharField(max_length=100, verbose_name='name (Uzbek)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='name (Russian)')),
                ('image', models.ImageField(blank=True, help_text='Square illustration / photo for buyer-side category cards', null=True, upload_to='categories/%Y/', verbose_name='image')),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='Lower = shown first in the buyer category grid', verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to retire a category without deleting its row', verbose_name='active')),
            ],
            options={
                'verbose_name': 'meat category',
                'verbose_name_plural': 'meat categories',
                'ordering': ('display_order', 'name_uz'),
            },
        ),
    ]
