# Generated by Django 5.2.14 on 2026-05-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_seed_meat_categories'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-created_at',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_li_status_c77037_idx',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Top-level facet — buyers filter by this', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.meatcategory'),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='description (Russian)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='description (Uzbek)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='market',
            field=models.ForeignKey(blank=True, help_text='The vendor that owns this listing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='markets.market'),
        ),
        migrations.AddField(
            model_name='listing',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='name (Russian)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='name (Uzbek)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe key; auto-generated from name_uz if left blank', max_length=140, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cold_chain',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold chain (deprecated)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, verbose_name='description (deprecated)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='freshness_date',
            field=models.DateField(blank=True, null=True, verbose_name='freshness date (deprecated)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='halal_certified',
            field=models.BooleanField(default=False, verbose_name='halal certified (deprecated)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, db_index=True, help_text='Per-listing location override; usually inherits from market.address', max_length=200, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='meat_type',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='meat type (deprecated)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='service_area_csv',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='service areas (deprecated)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('OUT_OF_STOCK', 'Out of stock'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='title (deprecated)'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'category'], name='listing_status_category_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['market', 'status'], name='listing_market_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__gt', '')), fields=('market', 'slug'), name='uniq_market_slug'),
        ),
    ]
