# Generated by Django 5.2.14 on 2026-05-20 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_refactor_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Russian translation; falls back to Uzbek if empty', max_length=200, verbose_name='name (Russian)'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='old price')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='new price')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes_made', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listings.listing')),
            ],
            options={
                'verbose_name': 'price history entry',
                'verbose_name_plural': 'price history',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['listing', '-created_at'], name='price_hist_listing_recent_idx')],
            },
        ),
    ]
