# Generated by Django 5.2.14 on 2026-05-20 19:18

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_add_price_history'),
        ('markets', '0002_historicalmarket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalListing',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe key; auto-generated from name_uz if left blank', max_length=140, verbose_name='slug')),
                ('name_uz', models.CharField(max_length=200, verbose_name='name (Uzbek)')),
                ('name_ru', models.CharField(blank=True, help_text='Russian translation; falls back to Uzbek if empty', max_length=200, verbose_name='name (Russian)')),
                ('description_uz', models.TextField(blank=True, verbose_name='description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, verbose_name='description (Russian)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per kg')),
                ('location', models.CharField(blank=True, db_index=True, help_text='Per-listing location override; usually inherits from market.address', max_length=200, verbose_name='location')),
                ('available_from', models.DateField(verbose_name='available from')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OUT_OF_STOCK', 'Out of stock'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=15, verbose_name='status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='Top-level facet — buyers filter by this', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='listings.meatcategory')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(blank=True, db_constraint=False, help_text='The vendor that owns this listing', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='markets.market')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
