# Generated by Django 5.2.14 on 2026-06-15 18:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_create_catalog_rbac_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='breed_type',
            field=models.CharField(blank=True, db_index=True, help_text='Hisor, Shved, Gissar etc. — live animals only; blank for raw meat', max_length=80, verbose_name='breed'),
        ),
        migrations.AddField(
            model_name='historicallisting',
            name='estimated_meat_yield_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='Live-only: 0-100 (0 = N/A for raw meat). 55 means a 100kg animal yields ~55kg of finished meat', verbose_name='estimated meat yield %'),
        ),
        migrations.AddField(
            model_name='historicallisting',
            name='head_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of animals available — only used when sale_type=BY_HEAD', verbose_name='head count'),
        ),
        migrations.AddField(
            model_name='historicallisting',
            name='is_live_animal',
            field=models.BooleanField(db_index=True, default=False, help_text='True = tirik chorva (live cow/sheep/horse); False = raw meat', verbose_name='is live animal'),
        ),
        migrations.AddField(
            model_name='historicallisting',
            name='live_weight_per_head_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average live weight per animal for BY_HEAD listings', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='live weight per head (kg)'),
        ),
        migrations.AddField(
            model_name='historicallisting',
            name='sale_type',
            field=models.CharField(choices=[('BY_WEIGHT', 'By weight (kg)'), ('BY_HEAD', 'By head (per animal)')], default='BY_WEIGHT', help_text='BY_HEAD = sold per animal; BY_WEIGHT = sold per kg (raw meat OR live by kg)', max_length=10, verbose_name='sale type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='breed_type',
            field=models.CharField(blank=True, db_index=True, help_text='Hisor, Shved, Gissar etc. — live animals only; blank for raw meat', max_length=80, verbose_name='breed'),
        ),
        migrations.AddField(
            model_name='listing',
            name='estimated_meat_yield_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='Live-only: 0-100 (0 = N/A for raw meat). 55 means a 100kg animal yields ~55kg of finished meat', verbose_name='estimated meat yield %'),
        ),
        migrations.AddField(
            model_name='listing',
            name='head_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of animals available — only used when sale_type=BY_HEAD', verbose_name='head count'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_live_animal',
            field=models.BooleanField(db_index=True, default=False, help_text='True = tirik chorva (live cow/sheep/horse); False = raw meat', verbose_name='is live animal'),
        ),
        migrations.AddField(
            model_name='listing',
            name='live_weight_per_head_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average live weight per animal for BY_HEAD listings', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='live weight per head (kg)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('BY_WEIGHT', 'By weight (kg)'), ('BY_HEAD', 'By head (per animal)')], default='BY_WEIGHT', help_text='BY_HEAD = sold per animal; BY_WEIGHT = sold per kg (raw meat OR live by kg)', max_length=10, verbose_name='sale type'),
        ),
    ]
