# Generated by Django 5.2.14 on 2026-06-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_historicallisting_breed_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='animal_form',
            field=models.CharField(choices=[('LIVE', 'Live animal'), ('RAW_CUT', 'Fresh ready meat (cut)'), ('BOTH', 'Both live + cut')], db_index=True, default='RAW_CUT', max_length=8, verbose_name='animal form'),
        ),
        migrations.AddField(
            model_name='listing',
            name='animal_form',
            field=models.CharField(choices=[('LIVE', 'Live animal'), ('RAW_CUT', 'Fresh ready meat (cut)'), ('BOTH', 'Both live + cut')], db_index=True, default='RAW_CUT', max_length=8, verbose_name='animal form'),
        ),
    ]
