# Generated by Django 5.2.14 on 2026-07-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_historicallisting_animal_form_listing_animal_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='supplier_delivers',
            field=models.BooleanField(default=False, help_text='Skip courier assignment — supplier delivers this listing themselves.', verbose_name='supplier does own delivery'),
        ),
        migrations.AddField(
            model_name='listing',
            name='supplier_delivers',
            field=models.BooleanField(default=False, help_text='Skip courier assignment — supplier delivers this listing themselves.', verbose_name='supplier does own delivery'),
        ),
    ]
