# Generated by Django 5.2.14 on 2026-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_historicallisting_supplier_delivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price range max'),
        ),
        migrations.AddField(
            model_name='historicallisting',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price range min'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price range max'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price range min'),
        ),
    ]
