# Generated by Django 5.2.14 on 2026-05-05 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SUPPLIER_VERIFIED', 'Supplier verified'), ('ORDER_PLACED', 'Order placed'), ('ORDER_STATUS_CHANGED', 'Order status changed'), ('ORDER_CANCELLED', 'Order cancelled'), ('OTHER', 'Other')], default='OTHER', max_length=24, verbose_name='kind')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='deep link')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='is read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
