# Generated by Django 5.2.14 on 2026-05-10 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_alter_buyerprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. Uy, Ofis, Restoran', max_length=50, verbose_name='label')),
                ('address', models.TextField(verbose_name='address')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved address',
                'verbose_name_plural': 'saved addresses',
                'ordering': ('-is_default', '-created_at'),
                'indexes': [models.Index(fields=['user', '-is_default'], name='buyers_save_user_id_a43d78_idx')],
            },
        ),
    ]
