# Generated by Django 5.2.14 on 2026-05-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_savedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='apartment',
            field=models.CharField(blank=True, help_text='Xonadon', max_length=20, verbose_name='apartment'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='entrance',
            field=models.CharField(blank=True, help_text="Kirish yo'lagi", max_length=20, verbose_name='entrance'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='floor',
            field=models.CharField(blank=True, help_text='Qavat', max_length=20, verbose_name='floor'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='notes',
            field=models.TextField(blank=True, help_text='Belgilangan joy va manzil tafsilotlari — helps the courier find you faster', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='address',
            field=models.TextField(help_text="Street line — e.g. 'Bobur mahalla fuqarolar yig'ini, 6'", verbose_name='address'),
        ),
    ]
