# Generated by Django 5.2.14 on 2026-06-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=20, verbose_name='payment provider'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider_tx_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='payment provider tx id'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='UNPAID', max_length=10, verbose_name='payment status'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='payment URL'),
        ),
    ]
