# Generated by Django 5.2.14 on 2026-06-15 18:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_provider_order_payment_provider_tx_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='butcher_service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='butcher service fee'),
        ),
        migrations.AddField(
            model_name='order',
            name='butcher_service_requested',
            field=models.BooleanField(default=False, verbose_name='butcher service requested'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='delivery distance (km)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='delivery latitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='delivery longitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='delivery price'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_slot',
            field=models.CharField(blank=True, choices=[('SLOT_0609', '06:00 – 09:00'), ('SLOT_0913', '09:00 – 13:00'), ('SLOT_1318', '13:00 – 18:00')], max_length=12, verbose_name='delivery time slot'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_vehicle_type',
            field=models.CharField(blank=True, choices=[('REFRIGERATOR', 'Refrigerator (cold-chain)'), ('CHORVA_TAXI', 'Chorva-Taksi (live animal)')], max_length=16, verbose_name='delivery vehicle type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('PROCESSING_BUTCHER', 'At butcher (slaughter & cut)'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
