# Generated by Django 5.2.14 on 2026-07-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_assigned_qassob_order_qassob_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('AWAITING_QASSOB', 'Awaiting qassob'), ('PROCESSING_BUTCHER', 'At butcher (slaughter & cut)'), ('IN_TRANSIT', 'In transit'), ('DELIVERED_PENDING_CONFIRMATION', 'Delivered — awaiting buyer confirmation'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32, verbose_name='status'),
        ),
    ]
