# Generated by Django 5.2.14 on 2026-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('AWAITING_CONTACT', 'Awaiting contact share'), ('CODE_SENT', 'Code sent'), ('VERIFIED', 'Verified')], db_index=True, default='AWAITING_CONTACT', max_length=20)),
                ('code_hash', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Telegram verification',
                'verbose_name_plural': 'Telegram verifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'status'], name='telegram_au_phone_122040_idx'), models.Index(fields=['phone', 'code_sent_at'], name='telegram_au_phone_e01708_idx')],
            },
        ),
    ]
