# Generated by Django 5.2.14 on 2026-07-07 17:32

import apps.couriers.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='full name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.couriers.models._courier_photo_path, verbose_name='photo')),
                ('vehicle_kind', models.CharField(choices=[('BIKE', 'Bike / motorbike'), ('CAR', 'Car'), ('VAN', 'Van / small truck'), ('REFRIGERATOR', 'Refrigerated van (cold-chain)'), ('CHORVA_TAXI', 'Chorva-Taksi (live animal transport)')], default='BIKE', max_length=16, verbose_name='vehicle')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, verbose_name='license plate')),
                ('is_online', models.BooleanField(db_index=True, default=False, verbose_name='online / accepting jobs')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='rating average')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='rating count')),
                ('lifetime_deliveries', models.PositiveIntegerField(default=0, verbose_name='lifetime deliveries')),
                ('lifetime_earnings_uzs', models.PositiveBigIntegerField(default=0, verbose_name='lifetime earnings (soum)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'courier profile',
                'verbose_name_plural': 'courier profiles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked up'), ('EN_ROUTE', 'En route'), ('ARRIVED', 'Arrived at drop-off'), ('DELIVERED', 'Delivered (courier-side)'), ('CANCELLED', 'Cancelled')], db_index=True, default='ASSIGNED', max_length=16, verbose_name='status')),
                ('cash_collected_uzs', models.PositiveBigIntegerField(default=0, verbose_name='cash collected (soum)')),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to=apps.couriers.models._delivery_proof_path, verbose_name='proof photo')),
                ('payout_uzs', models.PositiveBigIntegerField(default=0, verbose_name='courier payout (soum)')),
                ('buyer_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='buyer rating')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='picked up at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['courier', 'status'], name='couriers_de_courier_9a0675_idx')],
            },
        ),
    ]
