# Generated by Django 5.2.14 on 2026-05-10 22:30

import apps.suppliers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='about the business'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='phone_visible',
            field=models.BooleanField(default=True, help_text="If true, supplier's phone is shown on listing detail", verbose_name='show phone to buyers'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.suppliers.models._supplier_photo_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
