# Generated by Django 5.2.14 on 2026-06-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplierprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='animals_supported',
            field=models.JSONField(default=list, help_text='List of animal codes from MOL/QOY/ECHKI/OT/TOVUQ.', verbose_name='animals supported'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='delivery_modes',
            field=models.JSONField(default=dict, help_text='Per-animal map: {animal_code: [LIVE|CUT, ...]}.', verbose_name='delivery modes per animal'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='From Supplier wizard p2 — printed on the supplier card.', max_length=150, verbose_name='operator full name'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='is_open_now',
            field=models.BooleanField(db_index=True, default=True, verbose_name='open for orders now'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='rating average'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='rating count'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='self_delivers',
            field=models.BooleanField(default=False, verbose_name='self-delivers own orders'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='telegram username'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='vehicle plate number'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='vehicle_types',
            field=models.JSONField(default=list, help_text="['REFRIGERATOR'|'CHORVA_TAXI'] — only when self_delivers.", verbose_name='vehicle types'),
        ),
    ]
