# Generated by Django 5.2.14 on 2026-05-20 19:05

import apps.markets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-safe key; auto-generated from Uzbek name if left blank', max_length=120, unique=True, verbose_name='slug')),
                ('name_uz', models.CharField(max_length=200, verbose_name='name (Uzbek)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='name (Russian)')),
                ('description_uz', models.TextField(blank=True, verbose_name='description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, verbose_name='description (Russian)')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('region', models.CharField(db_index=True, help_text="e.g. Toshkent, Samarqand — drives 'near me' filtering", max_length=80, verbose_name='region')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('phone', models.CharField(blank=True, help_text="Used by support when buyers can't reach the market", max_length=20, verbose_name='phone')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='Per-day hours as {weekday: [open_hour, close_hour]} or null=closed', verbose_name='working hours')),
                ('logo', models.ImageField(blank=True, help_text='Square brand mark; shown on market cards + chat avatars', null=True, upload_to=apps.markets.models._market_logo_path, verbose_name='logo')),
                ('cover', models.ImageField(blank=True, help_text='Wide hero image on the market detail screen', null=True, upload_to=apps.markets.models._market_cover_path, verbose_name='cover photo')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide from buyers; row stays in DB for history', verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markets_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'market',
                'verbose_name_plural': 'markets',
                'ordering': ('name_uz',),
                'indexes': [models.Index(fields=['region', 'is_active'], name='market_region_active_idx')],
            },
        ),
    ]
