# Generated by Django 5.2.14 on 2026-05-20 19:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMarket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('slug', models.SlugField(help_text='URL-safe key; auto-generated from Uzbek name if left blank', max_length=120, verbose_name='slug')),
                ('name_uz', models.CharField(max_length=200, verbose_name='name (Uzbek)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='name (Russian)')),
                ('description_uz', models.TextField(blank=True, verbose_name='description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, verbose_name='description (Russian)')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('region', models.CharField(db_index=True, help_text="e.g. Toshkent, Samarqand — drives 'near me' filtering", max_length=80, verbose_name='region')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('phone', models.CharField(blank=True, help_text="Used by support when buyers can't reach the market", max_length=20, verbose_name='phone')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='Per-day hours as {weekday: [open_hour, close_hour]} or null=closed', verbose_name='working hours')),
                ('logo', models.TextField(blank=True, help_text='Square brand mark; shown on market cards + chat avatars', max_length=100, null=True, verbose_name='logo')),
                ('cover', models.TextField(blank=True, help_text='Wide hero image on the market detail screen', max_length=100, null=True, verbose_name='cover photo')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide from buyers; row stays in DB for history', verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical market',
                'verbose_name_plural': 'historical markets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
