# Generated by Django 5.2.14 on 2026-05-25 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_historicalmarket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmarket',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Backing SUPPLIER user — auto-created with the market; owns its listings', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='market',
            name='owner_user',
            field=models.OneToOneField(blank=True, help_text='Backing SUPPLIER user — auto-created with the market; owns its listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_market', to=settings.AUTH_USER_MODEL),
        ),
    ]
