# Generated by Django 5.2.14 on 2026-06-19 04:50

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth_user_first_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPPLIER', 'Supplier'), ('BUYER', 'Buyer'), ('QASSOB', 'Qassob')], default='BUYER', max_length=10, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PASSPORT', 'Passport / ID'), ('BUSINESS_LICENSE', 'Business license'), ('FACILITY_PHOTO', 'Facility / workplace photo'), ('OTHER', 'Other')], max_length=24, verbose_name='document type')),
                ('image', models.ImageField(upload_to=apps.accounts.models.kyc_upload_path, verbose_name='scan / photo')),
                ('admin_notes', models.TextField(blank=True, help_text='Private — visible only to admins. Reason for approval/rejection.', verbose_name='admin notes')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='approved')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC document',
                'verbose_name_plural': 'KYC documents',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='uniq_kyc_doc_per_kind')],
            },
        ),
    ]
