# Generated by Django 5.2.14 on 2026-07-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_kycdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPPLIER', 'Supplier'), ('BUYER', 'Buyer'), ('QASSOB', 'Qassob'), ('COURIER', 'Courier')], default='BUYER', max_length=10, verbose_name='role'),
        ),
    ]
