# Generated by Django 5.2.14 on 2026-06-19 04:50

import apps.qassobs.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QassobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Wizard p3 — overrides User.full_name on the buyer-facing card.', max_length=150, verbose_name='full name')),
                ('years_experience', models.PositiveSmallIntegerField(help_text='Wizard p2 — wheel picker 0-50. Used as a trust signal on the Servislar card.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='years of experience')),
                ('region', models.CharField(help_text='Reverse-geocoded from lat/lng on signup.', max_length=100, verbose_name='region')),
                ('address', models.TextField(verbose_name='street address')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('service_radius_km', models.PositiveSmallIntegerField(default=15, help_text='How far the qassob is willing to travel for live-animal pickup.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='service radius (km)')),
                ('animals_supported', models.JSONField(default=list, help_text='List of animal codes — subset of MOL/QOY/ECHKI/OT.', verbose_name='animals supported')),
                ('is_slaughterhouse', models.BooleanField(db_index=True, default=False, verbose_name='has slaughterhouse (qushxona)')),
                ('daily_capacity_head', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='daily capacity (heads)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.qassobs.models.qassob_photo_path, verbose_name='workplace photo')),
                ('phone_visible', models.BooleanField(default=True, help_text='If False, buyers contact via in-app chat only.', verbose_name='show phone publicly')),
                ('telegram_username', models.CharField(blank=True, help_text="Optional — enables the 'Telegram orqali bog'lanish' button.", max_length=64, verbose_name='telegram username')),
                ('is_open_now', models.BooleanField(db_index=True, default=True, verbose_name='open for jobs now')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='rating average')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='rating count')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='verified by admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qassob_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'qassob profile',
                'verbose_name_plural': 'qassob profiles',
                'ordering': ('-rating_avg', '-created_at'),
                'indexes': [models.Index(fields=['is_verified', 'region', '-rating_avg'], name='qassob_search_idx')],
            },
        ),
    ]
