# Generated by Django 5.2.14 on 2026-06-25 20:34

import apps.qassobs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qassobs', '0002_autoverify_all_qassobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='qassobprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Free-form description: who you are, family business history, what makes you different. Shown above the structured sections.', max_length=2000, verbose_name='about / bio'),
        ),
        migrations.AddField(
            model_name='qassobprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of {name, year} dicts. year is optional.', verbose_name='certifications'),
        ),
        migrations.AddField(
            model_name='qassobprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="List of ISO codes: ['uz', 'ru', 'en', 'tg'].", verbose_name='languages spoken'),
        ),
        migrations.AddField(
            model_name='qassobprofile',
            name='price_list',
            field=models.JSONField(blank=True, default=list, help_text="List of {service, price_uzs, unit} dicts. Example: [{'service': 'Mol so\\'yish', 'price_uzs': 250000, 'unit': 'bosh'}]", verbose_name='price list'),
        ),
        migrations.AddField(
            model_name='qassobprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text="List of short strings — e.g. ['Qurbonlik', 'Halal', 'Ekspress so\\'yish']. Rendered as chips on the buyer card.", verbose_name='specialties'),
        ),
        migrations.AddField(
            model_name='qassobprofile',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Per-weekday hours: {mon: [9, 21], tue: [9, 21], sun: null}. null = closed that day.', verbose_name='working hours'),
        ),
        migrations.CreateModel(
            name='QassobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.qassobs.models.qassob_gallery_photo_path, verbose_name='image')),
                ('caption', models.CharField(blank=True, help_text='Optional short caption shown under the photo.', max_length=200, verbose_name='caption')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Display order; lower numbers appear first.', verbose_name='position')),
                ('qassob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='qassobs.qassobprofile')),
            ],
            options={
                'verbose_name': 'qassob photo',
                'verbose_name_plural': 'qassob photos',
                'ordering': ('position', 'created_at'),
            },
        ),
    ]
