# Generated by Django 5.2.14 on 2026-06-15 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_4', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Must be 4 digits.')], verbose_name='last 4 digits')),
                ('brand', models.CharField(choices=[('HUMO', 'HUMO'), ('UZCARD', 'UZCARD'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12, verbose_name='brand')),
                ('expires_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='expires month')),
                ('expires_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2099)], verbose_name='expires year (YYYY)')),
                ('holder_name', models.CharField(blank=True, max_length=80, verbose_name='holder name')),
                ('phone_for_sms', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Must be a phone number.')], verbose_name='phone for SMS')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='default')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='provider')),
                ('provider_card_token', models.CharField(blank=True, max_length=128, verbose_name='provider card token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment card',
                'verbose_name_plural': 'payment cards',
                'ordering': ('-is_default', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='uniq_default_card_per_user')],
            },
        ),
    ]
